-- Seed the remaining worldwide export markets onto the contact map.
-- Source: "Worldwide Email Addresses.xlsx" (Elysée export desk list).
-- The 16 curated rows from 0005 (HQ + subsidiaries + key partners) are left
-- untouched: this migration only adds the export-only partner countries.
-- Each routes via the Cyprus Export Department; the regional Area Manager
-- (where one exists) is recorded in `note`. lat/lng are capital-city markers.
-- Idempotent: re-runs are no-ops via the PK conflict clause.
insert into public.countries
  (code, country, label, kind, lat, lng, nudge_x, nudge_y,
   address, phone, email, website, note, prefilled_message)
values
('dz', 'Algeria', 'Algeria', 'partner',
 36.7538, 3.0588, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · MENA Manager: menasales@elyseepipingsystems.co.uk',
 'Hi Elysée — I am enquiring from Algeria. Please put me in touch with your local distributor or representative.'),

('ai', 'Anguilla', 'Anguilla', 'partner',
 18.2206, -63.0686, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Anguilla. Please put me in touch with your local distributor or representative.'),

('ar', 'Argentina', 'Argentina', 'partner',
 -34.6037, -58.3816, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Latin America Manager: ventasla@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Argentina. Please put me in touch with your local distributor or representative.'),

('am', 'Armenia', 'Armenia', 'partner',
 40.1792, 44.4991, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · East Europe Manager: saleseasteurope@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Armenia. Please put me in touch with your local distributor or representative.'),

('by', 'Belarus', 'Belarus', 'partner',
 53.9006, 27.559, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · East Europe Manager: saleseasteurope@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Belarus. Please put me in touch with your local distributor or representative.'),

('be', 'Belgium', 'Belgium', 'partner',
 50.8503, 4.3517, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Belgium. Please put me in touch with your local distributor or representative.'),

('bo', 'Bolivia', 'Bolivia', 'partner',
 -16.4897, -68.1193, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Latin America Manager: ventasla@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Bolivia. Please put me in touch with your local distributor or representative.'),

('ba', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'partner',
 43.8563, 18.4131, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Bosnia and Herzegovina. Please put me in touch with your local distributor or representative.'),

('bw', 'Botswana', 'Botswana', 'partner',
 -24.6282, 25.9231, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Overseas Manager: salesoverseas@elysee.com.cy',
 'Hi Elysée — I am enquiring from Botswana. Please put me in touch with your local distributor or representative.'),

('br', 'Brazil', 'Brazil', 'partner',
 -15.7939, -47.8828, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Latin America Manager: ventasla@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Brazil. Please put me in touch with your local distributor or representative.'),

('bg', 'Bulgaria', 'Bulgaria', 'partner',
 42.6977, 23.3219, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Bulgaria. Please put me in touch with your local distributor or representative.'),

('cf', 'Central African Republic', 'Central African Republic', 'partner',
 4.3947, 18.5582, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Central African Republic. Please put me in touch with your local distributor or representative.'),

('cl', 'Chile', 'Chile', 'partner',
 -33.4489, -70.6693, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Latin America Manager: ventasla@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Chile. Please put me in touch with your local distributor or representative.'),

('cn', 'China', 'China', 'partner',
 39.9042, 116.4074, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from China. Please put me in touch with your local distributor or representative.'),

('co', 'Colombia', 'Colombia', 'partner',
 4.711, -74.0721, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Latin America Manager: ventasla@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Colombia. Please put me in touch with your local distributor or representative.'),

('cr', 'Costa Rica', 'Costa Rica', 'partner',
 9.9281, -84.0907, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Costa Rica. Please put me in touch with your local distributor or representative.'),

('hr', 'Croatia', 'Croatia', 'partner',
 45.815, 15.9819, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Croatia. Please put me in touch with your local distributor or representative.'),

('cz', 'Czech Republic', 'Czech Republic', 'partner',
 50.0755, 14.4378, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Czech Republic. Please put me in touch with your local distributor or representative.'),

('dk', 'Denmark', 'Denmark', 'partner',
 55.6761, 12.5683, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · East Europe Manager: saleseasteurope@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Denmark. Please put me in touch with your local distributor or representative.'),

('ec', 'Ecuador', 'Ecuador', 'partner',
 -0.1807, -78.4678, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Latin America Manager: ventasla@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Ecuador. Please put me in touch with your local distributor or representative.'),

('fi', 'Finland', 'Finland', 'partner',
 60.1699, 24.9384, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · East Europe Manager: saleseasteurope@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Finland. Please put me in touch with your local distributor or representative.'),

('gm', 'Gambia', 'Gambia', 'partner',
 13.4549, -16.579, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Gambia. Please put me in touch with your local distributor or representative.'),

('ge', 'Georgia', 'Georgia', 'partner',
 41.7151, 44.8271, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Georgia. Please put me in touch with your local distributor or representative.'),

('gh', 'Ghana', 'Ghana', 'partner',
 5.6037, -0.187, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Overseas Manager: salesoverseas@elysee.com.cy',
 'Hi Elysée — I am enquiring from Ghana. Please put me in touch with your local distributor or representative.'),

('hn', 'Honduras', 'Honduras', 'partner',
 14.0723, -87.1921, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Latin America Manager: ventasla@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Honduras. Please put me in touch with your local distributor or representative.'),

('hk', 'Hong Kong', 'Hong Kong', 'partner',
 22.3193, 114.1694, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Hong Kong. Please put me in touch with your local distributor or representative.'),

('hu', 'Hungary', 'Hungary', 'partner',
 47.4979, 19.0402, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Hungary. Please put me in touch with your local distributor or representative.'),

('is', 'Iceland', 'Iceland', 'partner',
 64.1466, -21.9426, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Iceland. Please put me in touch with your local distributor or representative.'),

('in', 'India', 'India', 'partner',
 28.6139, 77.209, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from India. Please put me in touch with your local distributor or representative.'),

('id', 'Indonesia', 'Indonesia', 'partner',
 -6.2088, 106.8456, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Indonesia. Please put me in touch with your local distributor or representative.'),

('ir', 'Iran', 'Iran', 'partner',
 35.6892, 51.389, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Iran. Please put me in touch with your local distributor or representative.'),

('iq', 'Iraq', 'Iraq', 'partner',
 33.3152, 44.3661, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · MENA Area Manager: menasales@elyseepipingsystems.co.uk',
 'Hi Elysée — I am enquiring from Iraq. Please put me in touch with your local distributor or representative.'),

('ie', 'Ireland', 'Ireland', 'partner',
 53.3498, -6.2603, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Ireland. Please put me in touch with your local distributor or representative.'),

('il', 'Israel', 'Israel', 'partner',
 31.7683, 35.2137, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Israel. Please put me in touch with your local distributor or representative.'),

('jo', 'Jordan', 'Jordan', 'partner',
 31.9454, 35.9284, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · MENA Area Manager: menasales@elyseepipingsystems.co.uk',
 'Hi Elysée — I am enquiring from Jordan. Please put me in touch with your local distributor or representative.'),

('kz', 'Kazakhstan', 'Kazakhstan', 'partner',
 51.1605, 71.4704, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · East Europe Manager: saleseasteurope@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Kazakhstan. Please put me in touch with your local distributor or representative.'),

('ke', 'Kenya', 'Kenya', 'partner',
 -1.2921, 36.8219, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Overseas Manager: salesoverseas@elysee.com.cy',
 'Hi Elysée — I am enquiring from Kenya. Please put me in touch with your local distributor or representative.'),

('kw', 'Kuwait', 'Kuwait', 'partner',
 29.3759, 47.9774, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · MENA Manager: menasales@elyseepipingsystems.co.uk',
 'Hi Elysée — I am enquiring from Kuwait. Please put me in touch with your local distributor or representative.'),

('lv', 'Latvia', 'Latvia', 'partner',
 56.9496, 24.1052, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · East Europe Manager: saleseasteurope@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Latvia. Please put me in touch with your local distributor or representative.'),

('lt', 'Lithuania', 'Lithuania', 'partner',
 54.6872, 25.2797, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · East Europe Manager: saleseasteurope@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Lithuania. Please put me in touch with your local distributor or representative.'),

('mk', 'North Macedonia', 'North Macedonia', 'partner',
 41.9981, 21.4254, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from North Macedonia. Please put me in touch with your local distributor or representative.'),

('my', 'Malaysia', 'Malaysia', 'partner',
 3.139, 101.6869, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Malaysia. Please put me in touch with your local distributor or representative.'),

('mt', 'Malta', 'Malta', 'partner',
 35.8989, 14.5146, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Malta. Please put me in touch with your local distributor or representative.'),

('mx', 'Mexico', 'Mexico', 'partner',
 19.4326, -99.1332, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Mexico Manager: ventas@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Mexico. Please put me in touch with your local distributor or representative.'),

('md', 'Moldova', 'Moldova', 'partner',
 47.0105, 28.8638, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Moldova. Please put me in touch with your local distributor or representative.'),

('mn', 'Mongolia', 'Mongolia', 'partner',
 47.8864, 106.9057, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Mongolia. Please put me in touch with your local distributor or representative.'),

('me', 'Montenegro', 'Montenegro', 'partner',
 42.4304, 19.2594, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Montenegro. Please put me in touch with your local distributor or representative.'),

('ma', 'Morocco', 'Morocco', 'partner',
 34.0209, -6.8416, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · MENA Manager: menasales@elyseepipingsystems.co.uk',
 'Hi Elysée — I am enquiring from Morocco. Please put me in touch with your local distributor or representative.'),

('mz', 'Mozambique', 'Mozambique', 'partner',
 -25.9692, 32.5732, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Mozambique. Please put me in touch with your local distributor or representative.'),

('nl', 'Netherlands', 'Netherlands', 'partner',
 52.3676, 4.9041, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Netherlands. Please put me in touch with your local distributor or representative.'),

('an', 'Netherlands Antilles', 'Netherlands Antilles', 'partner',
 12.1091, -68.9316, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Netherlands Antilles. Please put me in touch with your local distributor or representative.'),

('ng', 'Nigeria', 'Nigeria', 'partner',
 9.0765, 7.3986, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Nigeria. Please put me in touch with your local distributor or representative.'),

('no', 'Norway', 'Norway', 'partner',
 59.9139, 10.7522, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · East Europe Manager: saleseasteurope@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Norway. Please put me in touch with your local distributor or representative.'),

('om', 'Oman', 'Oman', 'partner',
 23.588, 58.3829, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · MENA Manager: menasales@elyseepipingsystems.co.uk',
 'Hi Elysée — I am enquiring from Oman. Please put me in touch with your local distributor or representative.'),

('py', 'Paraguay', 'Paraguay', 'partner',
 -25.2637, -57.5759, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Latin America Manager: ventasla@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Paraguay. Please put me in touch with your local distributor or representative.'),

('pe', 'Peru', 'Peru', 'partner',
 -12.0464, -77.0428, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Latin America Manager: ventasla@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Peru. Please put me in touch with your local distributor or representative.'),

('pl', 'Poland', 'Poland', 'partner',
 52.2297, 21.0122, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · East Europe Manager: saleseasteurope@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Poland. Please put me in touch with your local distributor or representative.'),

('qa', 'Qatar', 'Qatar', 'partner',
 25.2854, 51.531, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · MENA Manager: menasales@elyseepipingsystems.co.uk',
 'Hi Elysée — I am enquiring from Qatar. Please put me in touch with your local distributor or representative.'),

('ro', 'Romania', 'Romania', 'partner',
 44.4268, 26.1025, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Romania. Please put me in touch with your local distributor or representative.'),

('ru', 'Russia', 'Russia', 'partner',
 55.7558, 37.6173, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · East Europe Manager: saleseasteurope@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Russia. Please put me in touch with your local distributor or representative.'),

('rw', 'Rwanda', 'Rwanda', 'partner',
 -1.9706, 30.1044, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Rwanda. Please put me in touch with your local distributor or representative.'),

('sn', 'Senegal', 'Senegal', 'partner',
 14.7167, -17.4677, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Senegal. Please put me in touch with your local distributor or representative.'),

('rs', 'Serbia', 'Serbia', 'partner',
 44.7866, 20.4489, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Serbia. Please put me in touch with your local distributor or representative.'),

('sc', 'Seychelles', 'Seychelles', 'partner',
 -4.6191, 55.4513, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Overseas Manager: salesoverseas@elysee.com.cy',
 'Hi Elysée — I am enquiring from Seychelles. Please put me in touch with your local distributor or representative.'),

('sg', 'Singapore', 'Singapore', 'partner',
 1.3521, 103.8198, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Overseas Manager: salesoverseas@elysee.com.cy',
 'Hi Elysée — I am enquiring from Singapore. Please put me in touch with your local distributor or representative.'),

('sk', 'Slovakia', 'Slovakia', 'partner',
 48.1486, 17.1077, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Slovakia. Please put me in touch with your local distributor or representative.'),

('si', 'Slovenia', 'Slovenia', 'partner',
 46.0569, 14.5058, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Slovenia. Please put me in touch with your local distributor or representative.'),

('es', 'Spain', 'Spain', 'partner',
 40.4168, -3.7038, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Spain. Please put me in touch with your local distributor or representative.'),

('sd', 'Sudan', 'Sudan', 'partner',
 15.5007, 32.5599, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Sudan. Please put me in touch with your local distributor or representative.'),

('se', 'Sweden', 'Sweden', 'partner',
 59.3293, 18.0686, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · East Europe Manager: saleseasteurope@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Sweden. Please put me in touch with your local distributor or representative.'),

('ch', 'Switzerland', 'Switzerland', 'partner',
 46.948, 7.4474, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Elysée Rohrsysteme: info@elysee-rohrsysteme.com',
 'Hi Elysée — I am enquiring from Switzerland. Please put me in touch with your local distributor or representative.'),

('sy', 'Syria', 'Syria', 'partner',
 33.5138, 36.2765, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · MENA Manager: menasales@elyseepipingsystems.co.uk',
 'Hi Elysée — I am enquiring from Syria. Please put me in touch with your local distributor or representative.'),

('tw', 'Taiwan', 'Taiwan', 'partner',
 25.033, 121.5654, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Taiwan. Please put me in touch with your local distributor or representative.'),

('th', 'Thailand', 'Thailand', 'partner',
 13.7563, 100.5018, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Overseas Manager: salesoverseas@elysee.com.cy',
 'Hi Elysée — I am enquiring from Thailand. Please put me in touch with your local distributor or representative.'),

('tn', 'Tunisia', 'Tunisia', 'partner',
 36.8065, 10.1815, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · MENA Manager: menasales@elyseepipingsystems.co.uk',
 'Hi Elysée — I am enquiring from Tunisia. Please put me in touch with your local distributor or representative.'),

('ua', 'Ukraine', 'Ukraine', 'partner',
 50.4501, 30.5234, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Ukraine. Please put me in touch with your local distributor or representative.'),

('us', 'United States', 'United States', 'partner',
 38.9072, -77.0369, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from United States. Please put me in touch with your local distributor or representative.'),

('uy', 'Uruguay', 'Uruguay', 'partner',
 -34.9011, -56.1645, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Latin America Manager: ventasla@elyseepipingsystems.com',
 'Hi Elysée — I am enquiring from Uruguay. Please put me in touch with your local distributor or representative.'),

('ve', 'Venezuela', 'Venezuela', 'partner',
 10.4806, -66.9036, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department',
 'Hi Elysée — I am enquiring from Venezuela. Please put me in touch with your local distributor or representative.'),

('vn', 'Vietnam', 'Vietnam', 'partner',
 21.0285, 105.8542, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Overseas Manager: salesoverseas@elysee.com.cy',
 'Hi Elysée — I am enquiring from Vietnam. Please put me in touch with your local distributor or representative.'),

('zw', 'Zimbabwe', 'Zimbabwe', 'partner',
 -17.8252, 31.0335, null, null,
 E'5, Pentadaktylou street\n2643 Ergates Industrial Zone\nNicosia, Cyprus',
 '+357 22 455 008', 'yerolemos@elysee.com.cy', null,
 'Routed via the Cyprus Export Department · Overseas Manager: salesoverseas@elysee.com.cy',
 'Hi Elysée — I am enquiring from Zimbabwe. Please put me in touch with your local distributor or representative.')
on conflict (code) do nothing;
